version: '3'

tasks:
  # Source code quality

  fmt:
    desc: Format the source code using rustfmt
    silent: true
    cmds:
      - cargo fmt --all

  # Crates
  continuity-test:
    dir:  ./
    cmds:
        - cargo test --package pic-continuity
    silent: true

  pic-test:
    dir:  ./
    cmds:
        - cargo test --workspace
    silent: true

  pic-bench:
    dir:  ./
    cmds:
        -  cargo bench --workspace
    silent: true
